# Generated by Django 5.1.6 on 2025-02-08 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
